// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIi3QTQ49PRZ2ImGATpDG10qNYYyDzeuk',
    appId: '1:228490520879:web:d938cafc89e5da657ed9da',
    messagingSenderId: '228490520879',
    projectId: 'mealselection',
    authDomain: 'mealselection.firebaseapp.com',
    storageBucket: 'mealselection.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm5dlqDV4OJLomPvUi52K9MW3EHvvtIho',
    appId: '1:228490520879:android:edf6e04864108d267ed9da',
    messagingSenderId: '228490520879',
    projectId: 'mealselection',
    storageBucket: 'mealselection.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUvT1TdDxlnn2p-GhAXZELC6VhjzmSp9w',
    appId: '1:228490520879:ios:da3c60cd34278fb77ed9da',
    messagingSenderId: '228490520879',
    projectId: 'mealselection',
    storageBucket: 'mealselection.appspot.com',
    iosBundleId: 'com.example.mealselection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUvT1TdDxlnn2p-GhAXZELC6VhjzmSp9w',
    appId: '1:228490520879:ios:9008b9dec83c6cc37ed9da',
    messagingSenderId: '228490520879',
    projectId: 'mealselection',
    storageBucket: 'mealselection.appspot.com',
    iosBundleId: 'com.example.mealselection.RunnerTests',
  );
}
